on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*']

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@a440de3ab1dc824af7e6b9a256fe1a9fcf14c33a # v2.0.2
    with:
      push: ${{ github.event_name != 'pull_request' }}
