---
name: Linting
on:  # yamllint disable-line rule:truthy
  pull_request:

run-name: Pull request - ${{ github.event.pull_request.number }}
jobs:
  dockerlint:
    name: Lint - Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile

  markdownlint:
    name: Lint - Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Lint - Markdown
        uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16
        with:
          config: ".markdownlint.jsonc"
          globs: "**/*.md"

  yamllint:
    name: Lint - Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Lint - Yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
        with:
          config_file: .yamllint.yml
