---
name: Usage Test
on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_call:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  usage-test-amd64:
    name: Docker - Test (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: ${{ github.run_id }}
          platforms: linux/amd64

      - name: Run steamcmd
        run: |
            docker run --rm -it -d \
            -v ./palworld:/palworld \
            --stop-timeout 30 \
            ${{ github.run_id }} \
            +force_install_dir /palworld +login anonymous +app_update 2394010 validate +quit

  usage-test-arm64:
    name: Docker - Test (arm64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: ${{ github.run_id }}
          platforms: linux/arm64

      - name: Run steamcmd
        run: |
            docker run --rm -it -d \
            --platform linux/arm64 \
            -v ./palworld:/palworld \
            --stop-timeout 30 \
            ${{ github.run_id }} \
            +force_install_dir /palworld +login anonymous +app_update 2394010 validate +quit
