---
name: Usage Test
on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_call:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  usage-test-amd64:
    name: Usage test (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: steamcmd-amd64-${{ github.run_id }}
          outputs: type=docker,dest=/tmp/steamcmd-amd64-${{ github.run_id }}.tar
          platforms: linux/amd64

      - name: Load image
        run: docker load -i /tmp/steamcmd-amd64-${{ github.run_id }}.tar

      - name: Run steamcmd
        run: |
            docker run --rm -i \
            -v ./palworld:/palworld \
            --stop-timeout 30 \
            steamcmd-amd64-${{ github.run_id }} \
            +force_install_dir /palworld +login anonymous +app_update 2394010 validate +quit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: steamcmd-amd64-${{ github.run_id }}
          path: /tmp/steamcmd-amd64-${{ github.run_id }}.tar

  e2e-test-amd64:
    needs: usage-test-amd64
    name: End to end test (amd64)
    uses: USA-RedDragon/palworld-server-docker/.github/workflows/e2e-checks.yaml@main
    with:
      platform: amd64
      checkout: USA-RedDragon/palworld-server-docker
      load-image: steamcmd-amd64-${{ github.run_id }}
      load-image-repository: ${{ github.repository }}
      load-image-run-id: ${{ github.run_id }}
      build-args: |
        STEAMCMD_IMAGE=localhost:5000/steamcmd-amd64-${{ github.run_id }}

  usage-test-arm64:
    name: Usage test (arm64)
    runs-on: ubuntu-latest-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: steamcmd-arm64-${{ github.run_id }}
          outputs: type=docker,dest=/tmp/steamcmd-arm64-${{ github.run_id }}.tar
          platforms: linux/arm64

      - name: Load image
        run: docker load -i /tmp/steamcmd-arm64-${{ github.run_id }}.tar

      - name: Run steamcmd
        run: |
            docker run --rm -i \
            --platform linux/arm64 \
            -v ./palworld:/palworld \
            --stop-timeout 30 \
            steamcmd-arm64-${{ github.run_id }} \
            +force_install_dir /palworld +login anonymous +app_update 2394010 validate +quit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: steamcmd-arm64-${{ github.run_id }}
          path: /tmp/steamcmd-arm64-${{ github.run_id }}.tar

  e2e-test-arm64:
    needs: usage-test-arm64
    name: End to end test (arm64)
    uses: USA-RedDragon/palworld-server-docker/.github/workflows/e2e-checks.yaml@main
    with:
      platform: arm64
      load-image: steamcmd-arm64-${{ github.run_id }}
      load-image-repository: ${{ github.repository }}
      load-image-run-id: ${{ github.run_id }}
      checkout: USA-RedDragon/palworld-server-docker
      build-args: |
        STEAMCMD_IMAGE=localhost:5000/steamcmd-arm64-${{ github.run_id }}
